apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - postgres.yaml
  - server.yaml
  - frontend.yaml
  - collector.yaml
  - cloudflared.yaml
  - network-policy.yaml

images:
  - name: ghcr.io/bbssjj/itrend-collector
    newTag: manual
  - name: ghcr.io/bbssjj/itrend-server
    newTag: manual
  - name: ghcr.io/bbssjj/itrend-frontend
    newTag: manual

