apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itrend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BBSSJJ/itrend.git
    targetRevision: main
    path: deploy/quick
  destination:
    server: https://kubernetes.default.svc
    namespace: itrend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
